# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Vector logSumExpArma
#'
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
NULL

#' Vector logSumExp
#' 
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
#' @export
logSumExp <- function(x) {
    .Call('_epiAlleleGLM_logSumExp', PACKAGE = 'epiAlleleGLM', x)
}

marginalTransitionsCpp <- function(data, tMat, traversal, nTips, logPi, siblings, ncores = 1L) {
    .Call('_epiAlleleGLM_marginalTransitionsCpp', PACKAGE = 'epiAlleleGLM', data, tMat, traversal, nTips, logPi, siblings, ncores)
}

#' multiProbToStick 
#'
#' Convert a multiple sets of stick breaking parameters to a set of probabilities that sum to one
#' @param x the parameter of stick breaking parameters
#' @param width the width of the stick breakink process
#' @name multiProbToStick
#' @return a vector of probabilities that sum to one
multiProbToStick <- function(x, width) {
    .Call('_epiAlleleGLM_multiProbToStick', PACKAGE = 'epiAlleleGLM', x, width)
}

#' multiStickToProb 
#'
#' Convert a multiple sets of stick breaking parameters to a set of probabilities that sum to one
#' @param x the parameter of stick breaking parameters
#' @param width the width of the stick breakink process
#' @name multiStickToProb
#' @return a vector of probabilities that sum to one
multiStickToProb <- function(x, width) {
    .Call('_epiAlleleGLM_multiStickToProb', PACKAGE = 'epiAlleleGLM', x, width)
}

postorderMessagePassing <- function(data, tMat, traversal, nTips, logPi, nNode) {
    .Call('_epiAlleleGLM_postorderMessagePassing', PACKAGE = 'epiAlleleGLM', data, tMat, traversal, nTips, logPi, nNode)
}

preorderMessagePassing <- function(data, tMat, traversal, nTips, logPi, alpha, siblings, nNode, root) {
    .Call('_epiAlleleGLM_preorderMessagePassing', PACKAGE = 'epiAlleleGLM', data, tMat, traversal, nTips, logPi, alpha, siblings, nNode, root)
}

#' probToStick 
#'
#' Convert a set of probabilities that sum to one to a set of stick breaking parameters
#' @param x parameter vector of probabilities
#' @name probToStick
#' @return a vector of parameters for a stick breaking parameters
probToStick <- function(x) {
    .Call('_epiAlleleGLM_probToStick', PACKAGE = 'epiAlleleGLM', x)
}

setValues <- function(x, ind, val) {
    invisible(.Call('_epiAlleleGLM_setValues', PACKAGE = 'epiAlleleGLM', x, ind, val))
}

siteGainLossCpp <- function(data, tMat, traversal, nTips, logPi, siblings, ncores = 1L) {
    .Call('_epiAlleleGLM_siteGainLossCpp', PACKAGE = 'epiAlleleGLM', data, tMat, traversal, nTips, logPi, siblings, ncores)
}

#' stickToProb 
#'
#' Convert a set of stick breaking parameters to a set of probabilities that sum to one
#' @param x parameter vector of stick breaking process parameters
#' @name stickToProb
#' @return a vector of probabilities that sum to one
stickToProb <- function(x) {
    .Call('_epiAlleleGLM_stickToProb', PACKAGE = 'epiAlleleGLM', x)
}

treeLL <- function(data, tMat, traversal, nTips, logPi) {
    .Call('_epiAlleleGLM_treeLL', PACKAGE = 'epiAlleleGLM', data, tMat, traversal, nTips, logPi)
}

